### PR TITLE
General Improvements to Catan App

### PR DESCRIPTION
**Pull request by ben9583**
During the last board game social, some ideas were thrown around about how to make the Catan rolling app better. I've gone ahead and implemented a few of them, in addition to some other fixes:

- Update and fix `package.json`
- Reformat the website to look good on mobile and desktop
- Implement light and dark themes based on system preference
- Also implemented a manual toggle for light/dark theme
- Added an option to prevent the device from sleeping (so that the device owner doesn't have to keep unlocking the device)
- Added a truly random 2d6, as well as a truly random + bagged d12
- Included tooltips with explainers for features (hover on desktop, tap on mobile)

One thing that seemed to be a popular idea was to show the current status of the bag so that people wouldn't have to try and remember which numbers already came up. I haven't implemented that here because that seemed like a relatively big undertaking and I could see people disagreeing with the idea. Also I'm pretty tired.

A preview of the website can be viewed [here.](https://raspi.ben9583.com)

### CODE REVIEW

**Comment by ben9583** [comment]
Hmm, looks like the netlify deploy isn't working because it doesn't like `require()`, I'll see if I can do something about that.

**Comment by ben9583** [comment]
So looks like the CI isn't running again but it is up to date on [raspi.ben9583.com.](https://raspi.ben9583.com)

**Comment by 64bitpandas** [comment]
wow this looks awesome tysm for the improvements!!

played around with it for a few minutes, don't see any major issues. (C+K dark mode will still have black text though, but shouldn't be a big concern)

remember to bump the version number too lol

**Comment by ben9583** [comment]
Thanks! Good catch, I'll make those fixes now.

**Pull request merged**
